name: Pull Request Checks
on:
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle
      - name: Run Tests
        run: bash ./gradlew test
